// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybtlvczcjgylirhhmhhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlidGx2Y3pjamd5bGlyaGhtaGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDI0NzUsImV4cCI6MjA2ODUxODQ3NX0.rV3hJF_n7fjbNtzhAPDPm48e2qo7J9_zqT1WPTcGYZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});