// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igyvghhqbvpceafjuqaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlneXZnaGhxYnZwY2VhZmp1cWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzY2MTAsImV4cCI6MjA2ODM1MjYxMH0.uiorOUIzydo_wpcrLTDSLnp4aJJ9P5lFf8N_m36heIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});